# Generated by Django 4.0.4 on 2022-05-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_lap_creator_point_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='notes',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
