# Generated by Django 4.0.4 on 2022-05-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_activity_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='sport',
            field=models.CharField(choices=[('running', 'Running'), ('biking', 'Biking'), ('hiking', 'Hiking')], default='running', max_length=64),
        ),
    ]
