# Generated by Django 4.0.4 on 2022-05-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_alter_activity_sport_shoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
