# Generated by Django 4.0.4 on 2022-05-24 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_shoe_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='shoe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.shoe'),
        ),
    ]
