# Generated by Django 4.0.4 on 2022-06-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_activity_shoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
